# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoUi.ui'
#
# Created: Wed Aug 27 11:18:10 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_demoUi(object):
    def setupUi(self, demoUi):
        demoUi.setObjectName(_fromUtf8("demoUi"))
        demoUi.resize(514, 413)
        self.demoGroupBox = QtGui.QGroupBox(demoUi)
        self.demoGroupBox.setGeometry(QtCore.QRect(10, 120, 491, 281))
        self.demoGroupBox.setObjectName(_fromUtf8("demoGroupBox"))
        self.demoTabWidget = QtGui.QTabWidget(self.demoGroupBox)
        self.demoTabWidget.setGeometry(QtCore.QRect(10, 20, 471, 251))
        self.demoTabWidget.setObjectName(_fromUtf8("demoTabWidget"))
        self.basicTab = QtGui.QWidget()
        self.basicTab.setObjectName(_fromUtf8("basicTab"))
        self.testsuiteComboBox = QtGui.QComboBox(self.basicTab)
        self.testsuiteComboBox.setGeometry(QtCore.QRect(90, 10, 111, 22))
        self.testsuiteComboBox.setObjectName(_fromUtf8("testsuiteComboBox"))
        self.testsuiteLabel = QtGui.QLabel(self.basicTab)
        self.testsuiteLabel.setGeometry(QtCore.QRect(20, 11, 71, 21))
        self.testsuiteLabel.setObjectName(_fromUtf8("testsuiteLabel"))
        self.label = QtGui.QLabel(self.basicTab)
        self.label.setGeometry(QtCore.QRect(230, 10, 51, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.basicTab)
        self.lineEdit.setGeometry(QtCore.QRect(290, 10, 101, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.platformLabel = QtGui.QLabel(self.basicTab)
        self.platformLabel.setGeometry(QtCore.QRect(20, 51, 54, 21))
        self.platformLabel.setObjectName(_fromUtf8("platformLabel"))
        self.comboBox = QtGui.QComboBox(self.basicTab)
        self.comboBox.setGeometry(QtCore.QRect(90, 50, 111, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.targetLabel = QtGui.QLabel(self.basicTab)
        self.targetLabel.setGeometry(QtCore.QRect(230, 51, 54, 21))
        self.targetLabel.setObjectName(_fromUtf8("targetLabel"))
        self.targetComboBox = QtGui.QComboBox(self.basicTab)
        self.targetComboBox.setGeometry(QtCore.QRect(290, 50, 101, 22))
        self.targetComboBox.setObjectName(_fromUtf8("targetComboBox"))
        self.targetComboBox.addItem(_fromUtf8(""))
        self.targetComboBox.addItem(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/config_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.demoTabWidget.addTab(self.basicTab, icon, _fromUtf8(""))
        self.buildTab = QtGui.QWidget()
        self.buildTab.setObjectName(_fromUtf8("buildTab"))
        self.testDirLabel = QtGui.QLabel(self.buildTab)
        self.testDirLabel.setGeometry(QtCore.QRect(20, 10, 54, 21))
        self.testDirLabel.setObjectName(_fromUtf8("testDirLabel"))
        self.testLineEdit = QtGui.QLineEdit(self.buildTab)
        self.testLineEdit.setGeometry(QtCore.QRect(90, 10, 111, 20))
        self.testLineEdit.setObjectName(_fromUtf8("testLineEdit"))
        self.projectLabel = QtGui.QLabel(self.buildTab)
        self.projectLabel.setGeometry(QtCore.QRect(220, 10, 101, 20))
        self.projectLabel.setObjectName(_fromUtf8("projectLabel"))
        self.projectComboBox = QtGui.QComboBox(self.buildTab)
        self.projectComboBox.setGeometry(QtCore.QRect(330, 10, 69, 22))
        self.projectComboBox.setObjectName(_fromUtf8("projectComboBox"))
        self.projectComboBox.addItem(_fromUtf8(""))
        self.projectComboBox.addItem(_fromUtf8(""))
        self.libComboBox = QtGui.QComboBox(self.buildTab)
        self.libComboBox.setGeometry(QtCore.QRect(90, 50, 69, 22))
        self.libComboBox.setObjectName(_fromUtf8("libComboBox"))
        self.libComboBox.addItem(_fromUtf8(""))
        self.libComboBox.addItem(_fromUtf8(""))
        self.libLabel = QtGui.QLabel(self.buildTab)
        self.libLabel.setGeometry(QtCore.QRect(20, 50, 61, 20))
        self.libLabel.setObjectName(_fromUtf8("libLabel"))
        self.appInfoComboBox = QtGui.QComboBox(self.buildTab)
        self.appInfoComboBox.setGeometry(QtCore.QRect(330, 50, 69, 22))
        self.appInfoComboBox.setObjectName(_fromUtf8("appInfoComboBox"))
        self.appInfoComboBox.addItem(_fromUtf8(""))
        self.appInfoComboBox.addItem(_fromUtf8(""))
        self.appInfoLabel = QtGui.QLabel(self.buildTab)
        self.appInfoLabel.setGeometry(QtCore.QRect(220, 50, 61, 20))
        self.appInfoLabel.setObjectName(_fromUtf8("appInfoLabel"))
        self.ideLabel = QtGui.QLabel(self.buildTab)
        self.ideLabel.setGeometry(QtCore.QRect(20, 90, 21, 20))
        self.ideLabel.setObjectName(_fromUtf8("ideLabel"))
        self.ideComboBox = QtGui.QComboBox(self.buildTab)
        self.ideComboBox.setGeometry(QtCore.QRect(90, 90, 69, 22))
        self.ideComboBox.setObjectName(_fromUtf8("ideComboBox"))
        self.ideLineEdit = QtGui.QLineEdit(self.buildTab)
        self.ideLineEdit.setGeometry(QtCore.QRect(190, 90, 151, 20))
        self.ideLineEdit.setObjectName(_fromUtf8("ideLineEdit"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/build_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.demoTabWidget.addTab(self.buildTab, icon1, _fromUtf8(""))
        self.runTab = QtGui.QWidget()
        self.runTab.setObjectName(_fromUtf8("runTab"))
        self.debuggerLabel = QtGui.QLabel(self.runTab)
        self.debuggerLabel.setGeometry(QtCore.QRect(20, 10, 51, 21))
        self.debuggerLabel.setObjectName(_fromUtf8("debuggerLabel"))
        self.debuggerlineEdit = QtGui.QLineEdit(self.runTab)
        self.debuggerlineEdit.setGeometry(QtCore.QRect(190, 10, 241, 20))
        self.debuggerlineEdit.setObjectName(_fromUtf8("debuggerlineEdit"))
        self.debuggerComboBox = QtGui.QComboBox(self.runTab)
        self.debuggerComboBox.setGeometry(QtCore.QRect(90, 10, 69, 22))
        self.debuggerComboBox.setObjectName(_fromUtf8("debuggerComboBox"))
        self.serialLabel = QtGui.QLabel(self.runTab)
        self.serialLabel.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.serialLabel.setObjectName(_fromUtf8("serialLabel"))
        self.serialLineEdit = QtGui.QLineEdit(self.runTab)
        self.serialLineEdit.setGeometry(QtCore.QRect(100, 50, 113, 20))
        self.serialLineEdit.setObjectName(_fromUtf8("serialLineEdit"))
        self.debugLineEdit = QtGui.QLineEdit(self.runTab)
        self.debugLineEdit.setGeometry(QtCore.QRect(320, 50, 113, 20))
        self.debugLineEdit.setText(_fromUtf8(""))
        self.debugLineEdit.setObjectName(_fromUtf8("debugLineEdit"))
        self.debugLabel = QtGui.QLabel(self.runTab)
        self.debugLabel.setGeometry(QtCore.QRect(240, 50, 81, 21))
        self.debugLabel.setObjectName(_fromUtf8("debugLabel"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../pic/run_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.demoTabWidget.addTab(self.runTab, icon2, _fromUtf8(""))
        self.typeGroupBox = QtGui.QGroupBox(demoUi)
        self.typeGroupBox.setGeometry(QtCore.QRect(10, 60, 161, 51))
        self.typeGroupBox.setObjectName(_fromUtf8("typeGroupBox"))
        self.buildCheckBox = QtGui.QCheckBox(self.typeGroupBox)
        self.buildCheckBox.setGeometry(QtCore.QRect(20, 20, 51, 17))
        self.buildCheckBox.setObjectName(_fromUtf8("buildCheckBox"))
        self.runCheckBox = QtGui.QCheckBox(self.typeGroupBox)
        self.runCheckBox.setGeometry(QtCore.QRect(90, 20, 41, 17))
        self.runCheckBox.setObjectName(_fromUtf8("runCheckBox"))

        self.retranslateUi(demoUi)
        self.demoTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(demoUi)

    def retranslateUi(self, demoUi):
        demoUi.setWindowTitle(_translate("demoUi", "FreeKV_demo Configuration", None))
        self.demoGroupBox.setTitle(_translate("demoUi", "FreeKV_demo Configuration", None))
        self.testsuiteLabel.setText(_translate("demoUi", "Test Suite", None))
        self.label.setText(_translate("demoUi", "App Name", None))
        self.platformLabel.setText(_translate("demoUi", "Platform", None))
        self.targetLabel.setText(_translate("demoUi", "Target", None))
        self.targetComboBox.setItemText(0, _translate("demoUi", "Debug", None))
        self.targetComboBox.setItemText(1, _translate("demoUi", "Release", None))
        self.demoTabWidget.setTabText(self.demoTabWidget.indexOf(self.basicTab), _translate("demoUi", "Basic", None))
        self.testDirLabel.setText(_translate("demoUi", "Test Dir", None))
        self.projectLabel.setText(_translate("demoUi", "Generate Project", None))
        self.projectComboBox.setItemText(0, _translate("demoUi", "yes", None))
        self.projectComboBox.setItemText(1, _translate("demoUi", "no", None))
        self.libComboBox.setItemText(0, _translate("demoUi", "yes", None))
        self.libComboBox.setItemText(1, _translate("demoUi", "no", None))
        self.libLabel.setText(_translate("demoUi", "Build Lib", None))
        self.appInfoComboBox.setItemText(0, _translate("demoUi", "yes", None))
        self.appInfoComboBox.setItemText(1, _translate("demoUi", "no", None))
        self.appInfoLabel.setText(_translate("demoUi", "App Info", None))
        self.ideLabel.setText(_translate("demoUi", "IDE", None))
        self.demoTabWidget.setTabText(self.demoTabWidget.indexOf(self.buildTab), _translate("demoUi", "Build", None))
        self.debuggerLabel.setText(_translate("demoUi", "Debugger", None))
        self.serialLabel.setText(_translate("demoUi", "Serial Port", None))
        self.debugLabel.setText(_translate("demoUi", "Debug Port", None))
        self.demoTabWidget.setTabText(self.demoTabWidget.indexOf(self.runTab), _translate("demoUi", "Run", None))
        self.typeGroupBox.setTitle(_translate("demoUi", "Configuation Type", None))
        self.buildCheckBox.setText(_translate("demoUi", "Build", None))
        self.runCheckBox.setText(_translate("demoUi", "Run", None))

